// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urwupbyihwgaowikyedj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyd3VwYnlpaHdnYW93aWt5ZWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzU0OTQsImV4cCI6MjA2OTkxMTQ5NH0.RlP6LLly4mDDUPkYz1iZKjQ2m3AiPiqMGd7eZ_B1MsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});